# Generated by Django 4.2.7 on 2023-11-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdone',
            name='extraWork',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.employee'),
        ),
    ]
