# Generated by Django 4.2.7 on 2023-11-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_workdone_extrawork_alter_workdone_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdone',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.employee'),
        ),
    ]
