# Generated by Django 4.2.7 on 2023-11-28 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_employee_extrawork_employee_monthlydone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auto_delete',
            field=models.CharField(choices=[('one_day', 'One Day'), ('three_days', 'Three Days'), ('one_week', 'One Week'), ('one_month', 'One Month'), ('no_delete', "Don't Delete")], default='no_delete', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='notifications',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
