# Generated by Django 4.2.7 on 2023-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_employee_auto_delete_employee_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('outdated', models.BooleanField(default=False)),
                ('auto_delete', models.CharField(choices=[('one_day', 'One Day'), ('three_days', 'Three Days'), ('one_week', 'One Week'), ('one_month', 'One Month'), ('no_delete', "Don't Delete")], default='no_delete', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='auto_delete',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='outdated',
        ),
    ]
