# Generated by Django 4.2.7 on 2023-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_notifications_remove_employee_auto_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myconstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklyLimit', models.IntegerField(default=0)),
                ('monthlyLimit', models.IntegerField(default=0)),
                ('quotes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
