# Generated by Django 4.2.7 on 2023-11-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_myconstants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(blank=True, max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.employee')),
            ],
        ),
    ]
