# Generated by Django 4.2.7 on 2023-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_clientnumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
