# Generated by Django 4.2.7 on 2023-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_notifications_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='outdated',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='auto_delete',
            field=models.CharField(choices=[('one_day', 'One Day'), ('three_days', 'Three Days'), ('one_week', 'One Week'), ('one_month', 'One Month'), ('no_delete', "Don't Delete"), ('out_dated', 'out_dated')], default='no_delete', max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
