# Generated by Django 4.2.7 on 2023-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_notifications_outdated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnumber',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('no_response', 'No Response'), ('hold', 'Hold')], default='no_response', max_length=20),
        ),
    ]
