# Generated by Django 4.2.7 on 2023-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_clientnumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnumber',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('no_response', 'No Response'), ('hold', 'Hold'), (None, 'Null')], default=None, max_length=20),
        ),
    ]
