# Generated by Django 4.2.7 on 2023-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_clientnumber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnumber',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
