# Generated by Django 4.2.7 on 2023-12-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_rename_delete_employeemessage_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('clientnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.clientnumber')),
            ],
        ),
    ]
