# Generated by Django 4.2.7 on 2023-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_clientnumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnumber',
            name='status',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('no_response', 'No Response'), ('hold', 'Hold'), (None, 'Null')], max_length=20, null=True),
        ),
    ]
