# Generated by Django 4.2.7 on 2023-12-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_clientnumber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
